### ISSUE TITLE
import problem 

### ISSUE THREAD

**Issue by MrJico** [developmentforpeople/dfp_external_storage#11]
i would like to thank you first for this beautiful project, we currently have an issue with this module as we try to import data
it doesn't select the file so the import process doesn't start.

here is a screen shot of the error, i think this also happens  when in other places two.
![image](https://github.com/developmentforpeople/dfp_external_storage/assets/63163262/0bc34fb9-49d4-4c5f-8359-5f8d69b3214d)

**Comment by developmentforpeople** [comment]
Hi @MrJico! thanks for using this app and tell me about the issue :) Just made a fix for it, so you can update the app in your system and everything will be working fine when importing files. Take in mind that the rule is not tu upload to S3 any file used for being imported:

```py
		# Do not apply for Data Import files
		if self.attached_to_doctype in ("Data Import"):
			return False
```
Please tell me if everything works fine at your side ;)

**Comment by MrJico** [comment]
thanks for the quick reply, i will update my local version and test the solution.
