### ISSUE TITLE
ERPNext Report not working due to call of get_content on file in S3

### ISSUE THREAD

**Issue by khoran** [developmentforpeople/dfp_external_storage#12]
The built in "Stock Balance" report  (and likely other reports) in ERPNext is broken when using S3 for attachments. 

I have DFP External Storage configured to put all Attachments in S3 storage. When I open the Stock Balance report and click "Generate New Report", I get the error: "Cannot access file path /file/c6238a107c/2023-43-18-13:12.json.gz". Now that file does exist as a "File" record, and is stored in S3, as it should be. 

I dug into the code for the report. When you generate a report it runs the query in the background and then displays the content. The content is saved as a file (the one mentioned above), and this file is attached to a "Prepared Report" record type. When the report wants to display the query results, it fetches this Prepared Report (frappe.core.doctype.prepared_report.prepared_report.py) and calls `get_prepared_data()` on it. This function fetches the file attached to it (the above json file) as a "File" record, and then calls `get_content()` on it. This fails because the file does not exist locally, and the `get_content()` function is only defined on "File", but not on "DFPExternalStorageFile". Thus it does not know how to fetch the remote file contents and throws an exception. 

A quick search of frappe and erpnext shows many places where `get_content()` is called, so this could be a more widespread issue.

I'm not sure what the best way to fix this is, hence this issue. It seem like it might be necessary to override `get_content()` in DFPExternalStorageFile to catch this case and fetch the content for remote files correctly.

**Comment by developmentforpeople** [comment]
Hi @khoran thank you again for let me know your issues :). I just commit a fix for it (thanks to the extended info you gave me!), but not tested at my side (https://github.com/developmentforpeople/dfp_external_storage/commit/f7575dd46d0dd37aebc77fa596091aafe4b65b80). Please check that commit to understand how I resolved it. It just ignores using DFP External File Storage for files attached to "specified" doctypes. But I am with you and I will try to review all code and to find a global solution (if not at least manage what doctypes should be ignored,... 🤔). I will check asap, and let you know :) Stay in touch Kevin ;)

**Comment by developmentforpeople** [comment]
@khoran just checking the code and after the report is generated it is saved as json gzipped and attached as File here: https://github.com/developmentforpeople/frappe/blob/75c79925575e418e82083d6b1f22279c71d71a8f/frappe/client.py#L353
I will do my best ;)

**Comment by developmentforpeople** [comment]
@khoran hi again, resolved in different branch with this commit :) https://github.com/developmentforpeople/dfp_external_storage/commit/1c2d97a622745c07a1c334612b30072add1c517b
I will merge to develop probably this week after some more tests ;)

**Comment by khoran** [comment]
Great, that fixes the report issue! Thanks for the quick response.
