### ISSUE TITLE
attachment shearing not working 

### ISSUE THREAD

**Issue by MrJico** [developmentforpeople/dfp_external_storage#17]
when you share an attachment file with a user, the user can't view the content of the attachment and it doesn't give any errors.

![image](https://github.com/developmentforpeople/dfp_external_storage/assets/63163262/4861b64e-5a4c-4257-b947-26e3425e5360)

**Comment by developmentforpeople** [comment]
Hi @MrJico, thanks for share your error. I see the file in the screenshot is private, How do you share the file? could you give us more details, please? :) Thank you

**Comment by MrJico** [comment]
same as https://docs.erpnext.com/docs/user/manual/en/sharing
just for and attachemnt doc.
only the person who uploads the file can see it even if you share the file.

**Comment by developmentforpeople** [comment]
Yes I tried to replicate it and it happens, and happens without external storage selected too, with standard filesystem.
Please try at your side. So not an app issue, and a Frappe issue or I am not doing something wrong!

Please leave the field blank and save and check again with normal functionality:
![Screenshot from 2024-01-21 21-37-34](https://github.com/developmentforpeople/dfp_external_storage/assets/47140294/dde74988-06f0-4759-9152-a078bc4d4e38)

I shared like this:
![Screenshot from 2024-01-21 21-37-07](https://github.com/developmentforpeople/dfp_external_storage/assets/47140294/ef93d0bf-498e-49b1-ac67-1599639d23c1)

Thanks for your time @MrJico

**Comment by developmentforpeople** [comment]
@MrJico the doc is readable, but file is not downloable if private. You can see here:

For file being downloadable, Frappe checks this:
![Screenshot from 2024-01-21 21-43-58](https://github.com/developmentforpeople/dfp_external_storage/assets/47140294/b46f8db3-687a-48d6-a636-4f0c39631267)

Then, in this line, the value of `doc.is_private = 1`, so continue with next lines:
![Screenshot from 2024-01-21 21-45-18](https://github.com/developmentforpeople/dfp_external_storage/assets/47140294/f4419da9-f7f8-4074-a4ec-013d2301853d)

Then returns False (line 85) for `has_permission`:
![Screenshot from 2024-01-21 21-59-28](https://github.com/developmentforpeople/dfp_external_storage/assets/47140294/45b6755d-d10a-41c5-b969-87208ede47a1)

Then the file is not readable, (even you are reading the File document). Please add the issue to Frappe Framework or do a fix and a Pull Request to solve it :)

Thank you @MrJico

**Comment by MrJico** [comment]
thanks sir, i needed to verify on my side first, that really is a very bad short coming for frappe and erpnext, i will try to figure it out and make a pull request to the main frappe branch, other wise will just open a new issue for it.

**Comment by MrJico** [comment]
after a bit more digging i found out that if the file is not attached it doesn't check the permissions at all and just return false, so they don't check if the file is not attached, and it seems that the file and the attached files are different documents so the check fails. 

ie:
the file document is c01b712410
but the attachment is a394e02a15

**Comment by MrJico** [comment]
by checking if the document is shared, we can over come this with using `frappe.share.get_shared(
            doc.doctype, user=user, filters=[["share_name", "=", doc.name]]
        )`

![image](https://github.com/developmentforpeople/dfp_external_storage/assets/63163262/60d00877-e24e-417d-aad5-eb72597d93da)

can you please verify ?

**Comment by MrJico** [comment]
one other thing is that the user even if he has only read access, can toggle the is private flag, once then the permission manager kicks in for the next times, so this seems to be another bug in the system

**Comment by MrJico** [comment]
after a bit of digging i found the bug. it is due to the if statement
![image](https://github.com/developmentforpeople/dfp_external_storage/assets/63163262/9e0558ac-10ec-4b03-96b9-84fd6687f20d)

and to fix it simply adding another check will be sufficient
![image](https://github.com/developmentforpeople/dfp_external_storage/assets/63163262/3c770be1-0858-4323-9e73-9f8ceae19e48)

**Comment by MrJico** [comment]
any updates ?

**Comment by developmentforpeople** [comment]
Thankyou for your investigation @MrJico. Knowing that is not an issue of this repository, please do a pull request Frappe respository, please. Thanks again for your help :)

**Comment by MrJico** [comment]
thanks sir, i am not very familiar  with frappe so if you could just validate it, i will migrate this issue to frappe.

**Comment by developmentforpeople** [comment]
@MrJico not an DFP External Storage issue, but I am trying to help you. Things I need to replicate your issue correctly:

##  1. Screenshot of user roles, permissions and type of user

### Roles & permissions

![image](https://github.com/developmentforpeople/dfp_external_storage/assets/47140294/c3c4d004-0e9f-4a1e-9fd6-5dc646c45bc0)

### Type of user

![Screenshot from 2024-03-03 10-24-17](https://github.com/developmentforpeople/dfp_external_storage/assets/47140294/b56e4d28-a930-414f-aa52-4eee817d2bb1)

## Please, check what happens if you attach the file to other document user has access, what happens? Can it read it then?

## Tell me exactly your Frappe version and commit possition, please.

I do not want to close it yet and want to help you :) Thanks @MrJico

**Comment by MrJico** [comment]
if i understand you correctly, if you link the attachment to a document and the user has access to that document it has no problems, this only happens if the attachment is not linked to any document.

as for the version i don't think matters, because as far as i looked nothing has changed in the way they process files, but i use version 14 latest update on production, and docker for local at 9321153b793edda5b896d41d300812664533cf91

**Comment by developmentforpeople** [comment]
> if i understand you correctly, if you link the attachment to a document and the user has access to that document it has no problems, this only happens if the attachment is not linked to any document.

Yest that's it, could you check at your side, please?

**Comment by MrJico** [comment]
> > if i understand you correctly, if you link the attachment to a document and the user has access to that document it has no problems, this only happens if the attachment is not linked to any document.
> 
> Yest that's it, could you check at your side, please?

my answer is me describing how its now.

**Comment by developmentforpeople** [comment]
Not having personal free time to check it. I close because is not related to this app and related to how Frappe works sharing files internally.
