### ISSUE TITLE
URL must start with http:// or https://

### ISSUE THREAD

**Issue by peacebrowne** [developmentforpeople/dfp_external_storage#18]
Hi developmentforpeople, the last time I experienced this error: "URL must start with http:// or https://" I checked your issues and saw that the issue was resolved. So I decided to reinstall the application and after that I have still been experiencing the same error.

Whenever I try to attach a file from my s3bucket I get this error: "URL must start with http:// or https://".
Can you please help?

**Comment by peacebrowne** [comment]
![Uploading Screenshot from 2024-01-31 10-42-50.png…]()

**Comment by developmentforpeople** [comment]
@peacebrowne you closed it, is it solved for you? :)
