### ISSUE TITLE
duplicate file names

### ISSUE THREAD

**Issue by khoran** [developmentforpeople/dfp_external_storage#19]
ERP's built in file storage handles files with identical names by adding a random string to the file name and also including that in the `file_url` field. 

However, with S3 this behavior is not the same. The URL is made unique by using the `name` of the File document, but the object storage key only uses the `file_name` field, not including the unique `name` field of the File document. Thus, while ERP stores two different File documents, S3 is writing to the same file for both of them. 

The effect can be hidden by the cache for a time. If you've downloaded the first upload of a file, then it is cached using `name`. If you then upload another file with different content but the same file name, it will appear you can download the two different files with their own content correctly. But if you disable or clear the cache, then you can confirm that the first file has been overwritten by the second file. 

The issue seems to stem from the `dfp_external_storage_upload_file` function: 
```
                key = f"{frappe.local.site}/{self.file_name}"
		is_public = "/public" if not self.is_private else ""
		if not local_file:
			local_file = "./" + frappe.local.site + is_public + self.file_url

		try:
			if not os.path.exists(local_file):
				frappe.throw(_("Local file not found"))
			with open(local_file, "rb") as f:
				self.dfp_external_storage_client.put_object(
					bucket_name=self.dfp_external_storage_doc.bucket_name,
					object_name=key,
					data=f,
					length=os.path.getsize(local_file),
					# Meta removed because same s3 file can be used within different File docs
					# metadata={"frappe_file_id": self.name}
				)

			self.dfp_external_storage_s3_key = key
			self.dfp_external_storage = self.dfp_external_storage_doc.name
			self.file_url = f"/{DFP_EXTERNAL_STORAGE_URL_SEGMENT_FOR_FILE_LOAD}/{self.name}/{self.file_name}"

			if delete_file:
				os.remove(local_file)
			self.save()
		except Exception as e:
```
The `key` field is assigned the site name and file name, but not the unique `name` field. Then it is used as the `object_name` and saved as the `dfp_external_storage_s3_key`. 

Could this be changed to include the unique `name` field in the `key` as well?

**Comment by khoran** [comment]
This is actually more serious than I first realized. I just did some tests, and anytime I upload an attachment to a document in ERP, it will silently overwrite every other attachment of the same name on any other ERP document. This means that file names must be GLOBALLY unique to avoid data loss, which is not a reasonable requirement, as I imagine you'd agree.

**Comment by developmentforpeople** [comment]
Hi @khoran thanks again for your feedback. It is solved in "develop" branch (check this commit that solves it  https://github.com/developmentforpeople/dfp_external_storage/commit/b7554d9441e5949eb07a926fa6ebad57ced9d7ae).

Kevin, could you recheck at your side, please?

Frappe uses this suffix `suffix=self.content_hash[-6:]` for same names. I initially thought about check with S3 if key exists, but finally decided to add the File ID as unique identifier for file:
- *file url*: /file/7719b64f91/a.png
- *s3 key*: bucket-name/a-7719b64f91.png

What do you feel about this solution, any other ideas to improve it? :) Thank you very much Kevin

**Comment by developmentforpeople** [comment]
@khoran FYI I published new version with fix. Compared with previous one: https://github.com/developmentforpeople/dfp_external_storage/compare/v1.1.1...v1.1.2
Please check at your side, but seems to work perfectly in all my tests :)

**Comment by khoran** [comment]
@developmentforpeople It kind of works, but requires a hack for my situation. If you set the `content` field before saving, then it works. But I need to upload a file by using the `dfp_external_storage_upload_file` function directly, so that the content is streamed rather than held in memory. 

The catch is that `name` is not set at this point because the file has not been saved. That makes sense, but if I save the file first, I get a validation error from `validate_file_on_disk` because the `dfp_is_s3_remote_file` is false because `dfp_external_storage_s3_key` is not yet set because I tried to save it before calling `dfp_external_storage_upload_file`. So it's kind of a chicken and egg problem. 

I can work around it by setting `content` to some string, like "dummy content", then save it, which works now, and then call `dfp_external_storage_upload_file`. But I don't think that would be clear to a new user. 

You might   wonder how `file_url` was getting set correctly before, if `name` was not set. It actually was not getting set properly in the `dfp_external_storage_s3_key` function, but was getting 'fixed' by the `hook_file_before_save` function, so it still came out ok.

**Comment by khoran** [comment]
@developmentforpeople 
Actually, my work around doesn't work. It appears to save the file, but it ends up with the dummy content and ignores the file upload. When I save it the first time with "dummy content", it saves that content to s3 and sets `dfp_external_storage_s3_key`. Then, when I next call `dfp_external_storage_upload_file`, it sees that the s3 key is set and returns, doing nothing. So the current solution is not usable for me.

**Comment by developmentforpeople** [comment]
@khoran Hi Kevin, did you find a solution for the issue? I were looking for one and maybe you can set the self.file_name before uploading the file, checking at your side that is not duplicated in the ERP (in case you are worried for that) because is it needed the file content to get the content hash for that check. Here is how Frappe calculates the content hash:

```py
			with open(file_path, "rb") as f:
				self.content_hash = get_content_hash(f.read())
```
And look for int within "content_hash" in all File docs. I paste here some code within Frappe used to generate the file name (check in file.py within doctype File):

```py
			self.name = frappe.generate_hash(length=10)
...
			self.file_name = re.sub(r"/", "", self.file_name)
...
				self.file_name = generate_file_name(
					name=self.file_name,
					suffix=self.content_hash[-6:],
					is_private=self.is_private,
				)
...
```

Hope this helps you Kevin :) Have a good weekend!

**Comment by khoran** [comment]
@developmentforpeople Thanks for the info. I've so far just been appending a random string to my file names, but that is not guaranteed to be unique. I think what would be helpful is the ability to save the the file initially with no content at all, creating a unique File doc name. Then be able to call a function to set (and re-set later even) the contents of the file. Currently, it's not possible to call `dfp_external_storage_upload_file` a second time since it bails out if the storage key is already set. So maybe a differently name function could be created just for uploading from files (never from `content`). What do you think?

**Comment by khoran** [comment]
@developmentforpeople I still can't get past the issue I [described above](https://github.com/developmentforpeople/dfp_external_storage/issues/19#issuecomment-1979049096). 

Here is a simple reproduction, which I think is not too uncommon:
```
   file_doc = frappe.get_doc({
                "doctype":"File",
                "file_name":"test_file.txt",
                "folder":"Home/Audio"  #an S3 folder
            })

    with tempfile.NamedTemporaryFile(delete=False) as temp_file:
        temp_file.write(b"test content")
        temp_file.seek(0)
        file_doc.dfp_external_storage_upload_file(temp_file.name)
    file_doc.save()
```
No error is produced, but it results in a File with the file_url set to `/file/None/test_file.txt` and dfp_external_storage_s3_key set to `dev.galcom.local/test_file-None.txt`. When you attempt to download the file, you get a 404 not found error. So the file is effectivly lost, but without any errors produced until retrieval is attempted.

At the very least, I think `dfp_external_storage_upload_file` should check for `self.name` being None and throw an error. Ideally, when `name` is None, it could save itself to produce a name, and then proceed. I'm not sure if that is possible in that context. If not though, another function with the ability to upload a new file, whether or not `dfp_external_storage_s3_key` is set would be needed.

Thanks.
