### ISSUE TITLE
Nonetype has no attribute list object or put_object

### ISSUE THREAD

**Issue by vinceisip-globe** [developmentforpeople/dfp_external_storage#26]
![image](https://github.com/developmentforpeople/dfp_external_storage/assets/141212287/3f50e89e-f183-4727-b5ed-590873f1d210)

as per the screenshot, says it has this nonetype error thing that I had no idea how to debug

version - 15 erpnext - 14

In context, I just want to put my S3 buckets using this and also confused what is this host:port

**Comment by Kiel-Hyre** [comment]
version - 15 and erpnext

**Comment by MrJico** [comment]
hello, can you please provide a bit more detail,
from which page you got this error, doing what action,
and what branch are you  on right now.

**Comment by vinceisip-globe** [comment]
Hi,

I am using the version-15 of DFP

For apps:
- Frappe 14
- Erpnext 14
- hrms 14
- educ latest
- agriculture latest
- custom_app

I setup all the necessary fields for DFP in which I allocated in Home/  (Connected S3)

When I am trying to upload a file, it does not sync to cloud (I  know there will a cloud icon if it syncs) but there is none, I go to the detail view of the file and that linked the DFP, and save, and that error shows.

Also in DFP, the list file when click will show no type list_object

I am wondering if the host:port was incorrect, when I am trying to insert s3.amazonaws.com:443, it will show that the bucket is access denied, however if I put a random string it will just let it slide and that errors shows

**Comment by MrJico** [comment]
if you are using aws, host:port should be `s3.amazonaws.com` and make sure the the secure option is checked as show bellow., also make sure the bucket name is correct.
![image](https://github.com/developmentforpeople/dfp_external_storage/assets/63163262/713778bb-abe5-49ca-a207-da05d1f85bf2)

**Comment by vinceisip-globe** [comment]
Much appreciated, let me try this one, and get back to you

**Comment by developmentforpeople** [comment]
Hi @vinceisip-globe, could you attach the error logged within https://yourdomain/app/error-log, please?

**Comment by developmentforpeople** [comment]
Thanks for your help @MrJico! 😊

**Comment by vinceisip-globe** [comment]
@developmentforpeople  here it is 
![image](https://github.com/developmentforpeople/dfp_external_storage/assets/141212287/ae6606bf-6aa6-4f5c-906c-4cdaa3d09d94)

![image](https://github.com/developmentforpeople/dfp_external_storage/assets/141212287/4183f863-e82c-41e1-ab6c-e31b5366bcf1)

**Comment by vinceisip-globe** [comment]
@MrJico  yup integrated it, and it works. Many thanks
