### ISSUE TITLE
"DFP External Storage by Folder is not a valid parent DocType for DFP External Storage by Folder" - what can I do?

### ISSUE THREAD

**Issue by keithkhl** [developmentforpeople/dfp_external_storage#29]
I just (re-)installed DFP External Storage to my server, and I have below pop-up warning when I try to set up a new DFP External storage from settings.
- DFP External Storage by Folder is not a valid parent DocType for DFP External Storage by Folder

I can set up an S3 instance, but wonder if the error disables any functions that I am not aware of.

**Comment by keithkhl** [comment]
Even with superadmin account (the very first account from installation), I cannot have permission to the system.
I have tried to upload a few image files, but none of them are available in my S3.
Right before the file manager page in Frappe is loaded, I could see the list of files a fraction of seconds, but then I can only see 'Create a new File' button. Nothing more than that.

Seems like the best S3 integration solution among all Frappe apps, if it works. Hopefully I can use it soon.

I'm on ERPNext 15, in case you wonder.


---
Nothing to do with this issue ticket, but I wonder if enabling this app with S3 configuration can change default file storage from local to S3.

**Comment by keithkhl** [comment]
Works if folders are assigned by 'Administrator' account, the very account that was created right after installation.
With 'Home' folder being used as the main folder, the default storage becomes S3's bucket.

**Comment by developmentforpeople** [comment]
Hi @keithkhl thanks for the info and for the issue. I will add it to docs ;)

**Comment by keithkhl** [comment]
Would be much better if you can extend the capability to all admin accounts.

**Comment by developmentforpeople** [comment]
Hi again @keithkhl, please do the changes needed and create a pull request and I will merge them :)
