### ISSUE TITLE
DocType Permissions

### ISSUE THREAD

**Issue by hectorburciaga** [developmentforpeople/dfp_external_storage#3]
I am having issues with the app, when installed, I get a permission error. It says Access Denied DFP External Storage by Folder. For some reason I cannot set permissions for this DocType as it is a child object. Any ideas? Thanks in advance.

**Comment by developmentforpeople** [comment]
Hi @hectorburciaga ! thanks for try my app :) Could you answer me this questions for having more info, please?

- Are you in Frappe version-14 branch?
- If you create a new site and install the app to it, do you get the same error? (this point is important to verify if could be an app issue or is other app/setup related :)
- Could you attach some screenshots and more info about the setup you are trying to do (apps involved, permissions, roles, etc)?

Thank you @hectorburciaga !
