### ISSUE TITLE
Folder structure in S3

### ISSUE THREAD

**Issue by keithkhl** [developmentforpeople/dfp_external_storage#30]
Is there a way to replicate Frappe file's folder structure (via DFP S3 Storage) on S3?
File upload/access works pretty fast, but all files are stored in a single bucket without any folder structure. The structure is available only at Frappe level.

To give you an example, say I save an image file through Frappe+ DFP
- Frappe1: home/my_attachment/image1.jpg
- Frappe2: home/my_images/image2.jpg
- S3: mybucket/image1.jpg, mybucket/imag2.jpg

I am aware that S3 does not really honor typical folder structure, but above structure may create issues if identical file names are used later. At least, console access to S3 does not help me locating the files.

**Comment by developmentforpeople** [comment]
Hi @keithkhl actual implementation does not recreate folder structure in S3, sorry.
I have no clear what are you trying to do, but please check how the S3 key contains File ID/Name, and it is used all along, for file retrieval and storage in both sides (Frappe & S3). I hope you find below screenshots helpful :)

![Screenshot from 2024-12-22 11-22-30](https://github.com/user-attachments/assets/a174fc53-0fa7-455a-98b1-907d023a2ffb)

Please do not forget either that you can access DB table (tabFile) and you can find there all data you need, even files buckets and keys: 
![Screenshot from 2024-12-22 11-08-25](https://github.com/user-attachments/assets/ef15ee2f-d1fa-45c6-946f-48d2865dc390)

Hope this helps @keithkhl :)

**Comment by developmentforpeople** [comment]
I close because it is not an issue :)
