### ISSUE TITLE
Request Timeout before registering

### ISSUE THREAD

**Issue by Amein-Eskinder** [developmentforpeople/dfp_external_storage#31]
When I try to add my first DFP storage to aws s3 bucket after a while of loading I am getting request timeout message

![image](https://github.com/user-attachments/assets/aa8dd5f3-35b6-4610-8a6b-bb2abaaa2d9b)

![image](https://github.com/user-attachments/assets/69872b1f-537a-4d41-8029-12bf8921f10c)

**Comment by AmeinEskinder** [comment]
had to remove the port number and only put s3.amazonaws.com

**Comment by developmentforpeople** [comment]
Thanks for your feedback @Amein-Eskinder :)

**Comment by AmeinEskinder** [comment]
Chief I just DMed you over mail @developmentforpeople
