### ISSUE TITLE
accessing propery on self.dfp_external_storage_doc when it is None

### ISSUE THREAD

**Issue by khoran** [developmentforpeople/dfp_external_storage#4]
I installed this app and got an error about self.dfp_external_storage_doc.enabled being accessed on a "None" valued object. In looking at the code, this came from line 209 for doctype/dfp_external_storage/dfp_external_storage.py:

`if not self.dfp_external_storage_doc.enabled:`

The value self.dfp_external_storage is a function property which can sometimes return None, leading to the above error. So I suggest adding a guard to that statement, like: 
`if not (self.dfp_external_storage_doc and self.dfp_external_storage_doc.enabled):`

That fixed the bug for me and it has been working great since.

**Comment by developmentforpeople** [comment]
Implemented @khoran ! Thank you very much for contacting me with a solution :)
https://github.com/developmentforpeople/dfp_external_storage/commit/ac857a5e02a6fb0f9d9073bc56e3cdf8641ff6e4
I will be here for anything you need ;)
