### ISSUE TITLE
Feature: allow streaming file content directly to S3

### ISSUE THREAD

**Issue by khoran** [developmentforpeople/dfp_external_storage#7]
I'm willing to implement this feature if you're interested in it. But I thought it would be good to get your feedback on how best to go about it. 
I need to be able to store large files (over 2GB). Currently, the only way to save a file is to read its contents into memory and pass it through the `contents` field. This is not possible for large files without risking a system crash. I was thinking, if you create the file doc like this: 
```
file_doc = frappe.get_doc({
    "doctype":"File",
    "folder":"Home/Uploads",
    "file_name":"name_of_file"
 })
 ```
then before saving the document, some function is called to upload the content from a file in a temporary location or a byte stream. This could then be directly streamed to S3. Something like:
```
file_doc.set_contents(open(temp_file,"r+"))
```
or 
```
file_doc.set_contents(io.BytesIO(b'hello'))
```
Internally this could call dfp_external_storage_upload_file, but with another argument, which is the byte stream. 

Or do you see a better way to implement that?

**Comment by developmentforpeople** [comment]
Thank you very much for your work @khoran ! please if you make a new PR, do it over develop branch :) Thanks again!!

**Comment by khoran** [comment]
Thanks. Sure, I'll make sure to use develop next time, didn't think of that.
