### ISSUE TITLE
When simulating file losts on bucket images show 404 error

### ISSUE THREAD

**Issue by luisrms69** [developmentforpeople/dfp_external_storage#9]
I have tried the app for various scenarios, one of them being the total lost of the bucket.  

Steps
1. Delete all content from bucket
2. I then use the files from the replication bucket to simulate file recovery
3. I managed to get everything back (had to reconstruct DFP External Storage: S3 Key by adding the folder).  
4. Everything seemed to work fine but then i notice that the image files are not recognized (error 404).
5. I can move the files back to the server (private/Files or public/files folders) and they will show up, download and preview correctly.  I do not get any error from the app, it moves the file back to the server and deletes it from the bucket.
6. Asigning them back to the bucket shows again a 404 error (the file dissappears from server and appears on bucket as expected)
7. I re-checked the bucket and the files do exists.  But erpnext shows no preview and downloading generates a 404 error.

Actions taken

1. I tried optimizing again the file (while on the server, step 5) but still same error, i have confirmed this behavior with all "lost" image files and confirm that all other file types work perfect.  
2. Adding new images also works perfectly.

Using Backblaze b2 for bucket.

Regards 

Luis Montanaro

**Comment by developmentforpeople** [comment]
Thanks for the tests @luisrms69 I will check too locally :)

**Comment by developmentforpeople** [comment]
Hi @luisrms69, I checked at my side and everything works fine, as expected. Could you recheck please? The only important thing in Frappe > File doc is below files: 
![image](https://github.com/developmentforpeople/dfp_external_storage/assets/47140294/bec11c65-ad4b-4e1a-92ab-9f12e9ea3ebc)
Bucket and S3 key. If bucket settings and s3 key matches, everything works fine :) Hope this helps!
